features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
common_design_node_title:
  full: 0
  rss: 0
  search_index: 0
  search_result: 0
  teaser: 0
  token: 0
